# Generated by Django 4.2.4 on 2024-01-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_roads', '0002_character_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='charisma',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='health',
            new_name='battery',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='strength',
            new_name='esteem',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='wisdom',
            new_name='happiness',
        ),
        migrations.RemoveField(
            model_name='character',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='role',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='level',
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='ethnicity',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('European', 'European'), ('Asian', 'Asian'), ('Hispanic', 'Hispanic'), ('Middle Eastern', 'Middle Eastern')], default='random ethnicity', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.CharField(choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert')], default='extrovert/introvert', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='traits',
            field=models.CharField(choices=[('Communicator', 'Communicator'), ('Innovator', 'Innovator'), ('Motivator', 'Motivator'), ('Analyzer', 'Analyzer'), ('Networker', 'Networker'), ('Mentor', 'Mentor'), ('Strategist', 'Strategist'), ('Empath', 'Empath'), ('Visionary', 'Visionary'), ('Activist', 'Activist')], default='random trait', max_length=25),
        ),
        migrations.AddField(
            model_name='stats',
            name='influence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='rizz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='skills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='type_story',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Spiritual', 'Spiritual'), ('Wealth', 'Wealth'), ('Fame', 'Fame'), ('Normal', 'Normal')], max_length=25),
        ),
    ]
