# Generated by Django 4.2.4 on 2024-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_roads', '0003_rename_charisma_stats_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ethnicity',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('European', 'European'), ('Asian', 'Asian'), ('Hispanic', 'Hispanic'), ('Middle Eastern', 'Middle Eastern')], max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.CharField(choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='traits',
            field=models.CharField(choices=[('Communicator', 'Communicator'), ('Innovator', 'Innovator'), ('Motivator', 'Motivator'), ('Analyzer', 'Analyzer'), ('Networker', 'Networker'), ('Mentor', 'Mentor'), ('Strategist', 'Strategist'), ('Empath', 'Empath'), ('Visionary', 'Visionary'), ('Activist', 'Activist')], max_length=25),
        ),
    ]
