# Generated by Django 4.2.4 on 2024-01-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_roads', '0005_alter_character_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ethnicity',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('European', 'European'), ('Asian', 'Asian'), ('Hispanic', 'Hispanic'), ('Middle Eastern', 'Middle Eastern'), ('South Asian', 'South Asian')], max_length=20),
        ),
    ]
